// Embeds the dashboard (single HTML file built from the repo root) into src/app/appHtml.ts.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, '../../../Process-Fit-Assessment.html');
const target = resolve(here, '../src/app/appHtml.ts');
const html = readFileSync(source, 'utf8');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target,
  '// GENERATED by scripts/sync-app.mjs from Process-Fit-Assessment.html. Do not edit.\n' +
  'export const APP_HTML: string = ' + JSON.stringify(html) + ';\n');
console.log('Embedded ' + (html.length / 1024).toFixed(0) + ' KB from ' + source);
